import "./globals.css";
import type { Metadata } from "next";
import Navbar from "@/components/Navbar";
import { Geist, Geist_Mono, Playfair_Display, Poppins } from "next/font/google";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const playfair = Playfair_Display({
  subsets: ["latin"],
  variable: "--font-playfair",
});

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700"],
  variable: "--font-poppins",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} ${playfair.variable} ${poppins.variable} h-full antialiased`}
    >
      <body className={`${playfair.variable} ${poppins.variable} bg-[#FFFDF8]`}>
        <Navbar />
        {children}
      </body>
    </html>
  );
}
